### get liste personne
# @name ListPersonnes
// @no-log
GET http://localhost:8080/personnes

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
